SELECT SPL.PLICRI1_0 AS ITMREF_0, SPL.PRI_0 AS PRI_0
FROM TEB.SPRICLIST SPL
INNER JOIN TEB.SPRICFICH SPF ON SPF.PLI_0 = SPL.PLI_0 AND SPF.PLICRD_0 = SPL.PLICRD_0
INNER JOIN TEB.SPRICCONF SPC ON SPC.PLI_0 = SPL.PLI_0
WHERE SPL.PLI_0 = 'ZPPE'
  AND SPC.PLIENAFLG_0 = 2
  AND SPF.PLISTRDAT_0 <= CAST(GETDATE() AS DATE)
  AND SPF.PLIENDDAT_0 >= CAST(GETDATE() AS DATE)
